### ISSUE TITLE
Connection to Harbor off integrated OVA fails with 

### ISSUE THREAD

**Issue by lgayatri** [tobegit3hub/harbor-py#4]
My harbor is coming from the integrated OVA and uses HTTPS. With harbor-py , connection failed with below error.

root@Ubuntu-VIc:/home/vmlib/VIC/VIC/admiral-cli-0.9.1/bin/linux-i386# python test.py
Traceback (most recent call last):
  File "test.py", line 7, in <module>
    client = harborclient.HarborClient(host, user, password)
  File "/usr/local/lib/python2.7/dist-packages/harborclient/harborclient.py", line 17, in __init__
    self.session_id = self.login()
  File "/usr/local/lib/python2.7/dist-packages/harborclient/harborclient.py", line 26, in login
    'password': self.password})
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 110, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 56, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 487, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='10.133.154.169', port=80): Max retries exceeded with url: /login (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7fb90be1e110>: Failed to establish a new connection: [Errno 110] Connection timed out',))
Exception AttributeError: "'HarborClient' object has no attribute 'session_id'" in <bound method HarborClient.__del__ of <harborclient.harborclient.HarborClient object at 0x7fb90bdfaf50>> ignored
root@Ubuntu-VIc:/home/vmlib/VIC/VIC/admiral-cli-0.9.1/bin/linux-i386# cat test.py
from harborclient import harborclient

host = "10.133.154.169"
user = "admin"
password = "Admin!23"

client = harborclient.HarborClient(host, user, password)

client.get_projects()
client.get_users()
client.get_statistics()
client.get_top_accessed_repositories()
client.search("library")

**Comment by tobegit3hub** [comment]
Hi @lgayatri , would you open an issue in [harbor](https://github.com/vmware/harbor) because this project has been merged into the main repository.

**Comment by lgayatri** [comment]
Hi @tobegit3hub , 
I opened https://github.com/vmware/harbor/issues/2199
